from __future__ import annotations

LUCID_EXERCISES = [
    {
        "slug": "critical_state_testing_technique",
        "title": "Critical State Testing Technique",
        "source_book": "Exploring the World of Lucid Dreaming",
        "source_pages": [62, 71, 72],
        "source_images": [
            "2026-02-12 18.06.42.jpg",
            "2026-02-12 18.08.29.jpg",
            "2026-02-12 18.08.33.jpg",
        ],
        "lines": [
            "1. Plan when to test your state.",
            "Pick five to ten different occasions during the day to test your state.",
            "Choose situations that are connected to your dreamsigns or recurring dream themes.",
            "Whenever anything surprising, unlikely, or emotionally intense happens, test your state.",
            "If you have recurring anxiety dreams, use matching waking situations as triggers.",
            "Example triggers:",
            "- stepping into an elevator",
            "- speaking to your boss",
            "- seeing an attractive person",
            "- reading a typographical error",
            "- going to the bathroom",
            "Practice this at your selected times and whenever something dreamlike occurs.",
            "2. Test your state.",
            "Ask yourself: 'Am I dreaming or awake?'",
            "Do not ask automatically and reply mindlessly.",
            "Look for oddities or inconsistencies that might indicate you are dreaming.",
            "Think back over the last several minutes and test your memory continuity.",
            "Read some text twice and check whether it stays stable.",
            "Do not conclude you are awake unless you have solid proof.",
            "3. Imagine yourself dreaming.",
            "After testing, tell yourself: 'If I were dreaming right now, what would this be like?'",
            "Vividly imagine that what you are hearing, feeling, smelling, and seeing is a dream.",
            "Observe your environment carefully for your target dreamsigns.",
            "Imagine what it would be like if one of your dreamsigns appeared now.",
            "When the scene becomes vivid, resolve: 'The next time I'm dreaming, I will remember to recognize it.'",
            "4. Imagine doing what you intend to do in your lucid dream.",
            "Choose in advance what you want to do after becoming lucid.",
            "Continue the fantasy and imagine becoming lucid in the present scene.",
            "Experience yourself doing your chosen lucid action.",
            "Firmly resolve to recognize that you are dreaming and carry out that action next time.",
        ],
    },
    {
        "slug": "power_of_resolution_technique",
        "title": "Power of Resolution Technique",
        "source_book": "Exploring the World of Lucid Dreaming",
        "source_pages": [66],
        "source_images": ["2026-02-12 18.08.15.jpg"],
        "lines": [
            "1. Day practice.",
            "During the day, repeatedly remind yourself that experience is mind-constructed.",
            "Maintain the resolve that you will recognize the true nature of experience.",
            "2. Night practice.",
            "At bedtime, firmly resolve that you will remember to recognize the dream state.",
            "Set a clear intention to realize that the dream is not waking reality.",
            "Optionally, if this matches your personal practice, use prayer or symbolic support.",
            "Keep the intent simple, confident, and consistent each night.",
        ],
    },
    {
        "slug": "intention_technique",
        "title": "Intention Technique",
        "source_book": "Exploring the World of Lucid Dreaming",
        "source_pages": [69],
        "source_images": ["2026-02-12 18.08.25.jpg"],
        "lines": [
            "1. Resolve to recognize dreaming.",
            "In the early morning or during a later-night awakening, affirm your intention clearly.",
            "2. Visualize yourself recognizing dreaming.",
            "Imagine dream situations that would normally trigger recognition.",
            "Include your most common or favorite dreamsigns in the visualization.",
            "3. Imagine carrying out an intended dream action.",
            "Choose one specific action to do in the dream once lucid.",
            "A good choice is an action that itself functions as a dreamsign.",
            "Example: imagine flying and recognizing during flight that you are dreaming.",
            "While visualizing, firmly resolve to recognize the next time you are dreaming.",
        ],
    },
    {
        "slug": "prospective_memory_training",
        "title": "Prospective Memory Training",
        "source_book": "Exploring the World of Lucid Dreaming",
        "source_pages": [76, 77],
        "source_images": ["2026-02-12 18.08.37.jpg", "2026-02-12 18.08.40.jpg"],
        "lines": [
            "1. Read the day's targets.",
            "Use only the target set for the current day.",
            "Do not memorize all targets in advance.",
            "2. Look for your targets during the day.",
            "At each target event, perform a state test ('Am I dreaming?').",
            "Focus on noticing the event the next time it occurs.",
            "3. Keep track of target hits.",
            "At the end of the day, record how many targets you noticed.",
            "Log misses and note if some targets never occurred.",
            "4. Continue for at least one week.",
            "Continue until you hit most targets consistently.",
            "Then create your own target list and keep tracking progress.",
            "Daily Targets - Sunday:",
            "- The next time I see a pet or an animal",
            "- The next time I look at my face in a mirror",
            "- The next time I turn on a light",
            "- The next time I see a flower",
            "Daily Targets - Monday:",
            "- The next time I write anything down",
            "- The next time I feel pain",
            "- The next time I hear someone say my name",
            "- The next time I drink something",
            "Daily Targets - Tuesday:",
            "- The next time I see a traffic light",
            "- The next time I hear music",
            "- The next time I throw something in the garbage",
            "- The next time I hear laughter",
            "Daily Targets - Wednesday:",
            "- The next time I turn on a television or radio",
            "- The next time I see a vegetable",
            "- The next time I see a red car",
            "- The next time I handle money",
            "Daily Targets - Thursday:",
            "- The next time I read something other than this list",
            "- The next time I check the time",
            "- The next time I notice myself daydreaming",
            "- The next time I hear the telephone ringing",
            "Daily Targets - Friday:",
            "- The next time I open a door",
            "- The next time I see a bird",
            "- The next time I use the toilet after noon",
            "- The next time I see the stars",
            "Daily Targets - Saturday:",
            "- The next time I put a key in a lock",
            "- The next time I see an advertisement",
            "- The next time I eat anything after breakfast",
            "- The next time I see a bicycle",
        ],
    },
    {
        "slug": "mild_technique",
        "title": "MILD Technique",
        "source_book": "Exploring the World of Lucid Dreaming",
        "source_pages": [78, 79],
        "source_images": ["2026-02-12 18.08.43.jpg", "2026-02-12 18.08.46.jpg"],
        "lines": [
            "1. Set up dream recall.",
            "Before sleep, resolve to wake and recall dreams during the night.",
            "2. Recall your dream.",
            "On awakening from a dream period, recall as many details as possible.",
            "If drowsy, briefly arouse yourself before returning to sleep.",
            "3. Focus your intent.",
            "As you fall back asleep, concentrate on remembering to recognize that you are dreaming.",
            "Repeat mentally: 'Next time I'm dreaming, I want to remember I'm dreaming.'",
            "If distracted, release other thoughts and return to the intention.",
            "4. See yourself becoming lucid.",
            "Imagine re-entering the dream and recognizing a dreamsign.",
            "Say to yourself: 'I'm dreaming!' and continue the imagined dream.",
            "Imagine carrying out your planned lucid action once recognition occurs.",
            "5. Repeat.",
            "Repeat Steps 3 and 4 until the intention feels set.",
            "Then fall asleep with recognition intention as the last thought in mind.",
        ],
    },
]
